# Optional, but highly recommended. Generate via `openssl rand -hex 32`.
#  langfuse:
#    encryptionKey:
#      value: ""
langfuse:
  salt:
    value: secureSalt
  nextauth:
    secret:
      value: test

postgresql:
  auth:
    username: langfuse
    password: test

clickhouse:
  auth:
    password: test

redis:
  auth:
    password: test

s3:
  deploy: false
  bucket: langfuse
  region: us-east-1
  endpoint: http://minio.minio.svc.cluster.local:9000
  forcePathStyle: true
  accessKeyId:
    value: minio
  secretAccessKey:
    value: miniosecret